// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8b1HI28-mWsC-M0w9xqRLTPrtx1Kmxjs',
    appId: '1:1039513657127:web:fb89796e5be472e1b79302',
    messagingSenderId: '1039513657127',
    projectId: 'flutter-ai-chat-8b331',
    authDomain: 'flutter-ai-chat-8b331.firebaseapp.com',
    storageBucket: 'flutter-ai-chat-8b331.firebasestorage.app',
    measurementId: 'G-C08CYZ6XQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzSc8k04S1V0J9Mjy0mTLEbZvsxg0rKCQ',
    appId: '1:1039513657127:android:7173c29531bb350ab79302',
    messagingSenderId: '1039513657127',
    projectId: 'flutter-ai-chat-8b331',
    storageBucket: 'flutter-ai-chat-8b331.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD39QOsoD4LFw--_7PTLX59XpEyS5CAaT0',
    appId: '1:1039513657127:ios:f4f69b5c71706b88b79302',
    messagingSenderId: '1039513657127',
    projectId: 'flutter-ai-chat-8b331',
    storageBucket: 'flutter-ai-chat-8b331.firebasestorage.app',
    iosBundleId: 'com.example.flutterAiChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD39QOsoD4LFw--_7PTLX59XpEyS5CAaT0',
    appId: '1:1039513657127:ios:f4f69b5c71706b88b79302',
    messagingSenderId: '1039513657127',
    projectId: 'flutter-ai-chat-8b331',
    storageBucket: 'flutter-ai-chat-8b331.firebasestorage.app',
    iosBundleId: 'com.example.flutterAiChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8b1HI28-mWsC-M0w9xqRLTPrtx1Kmxjs',
    appId: '1:1039513657127:web:f72751a7263a32d4b79302',
    messagingSenderId: '1039513657127',
    projectId: 'flutter-ai-chat-8b331',
    authDomain: 'flutter-ai-chat-8b331.firebaseapp.com',
    storageBucket: 'flutter-ai-chat-8b331.firebasestorage.app',
    measurementId: 'G-DGB2T1JX3Q',
  );
}
