name: Build Android APK

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      flutter-version: ${{ steps.set-flutter-version.outputs.version }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set Flutter version
        id: set-flutter-version
        run: echo "version=3.32.5" >> $GITHUB_OUTPUT

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          cache: true

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Replace API key from GitHub Secrets
        run: sed -i "s|your_api_key|${{ secrets.HUGGINGFACE_API_KEY }}|g" .env

      - name: Upload .env file
        uses: actions/upload-artifact@v4
        with:
          name: env-file
          path: .env

  install_deps:
    runs-on: ubuntu-latest
    needs: prepare

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          cache: true

      - name: Download .env file
        uses: actions/download-artifact@v4
        with:
          name: env-file

      - name: Move .env to root
        run: mv env-file/.env .env

      - name: Install dependencies
        run: flutter pub get

  build_apk:
    runs-on: ubuntu-latest
    needs: install_deps

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          cache: true

      - name: Download .env file
        uses: actions/download-artifact@v4
        with:
          name: env-file

      - name: Move .env to root
        run: mv env-file/.env .env

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
