name: Build and Deploy Flutter Android App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5'
        channel: 'stable'
        
    - name: Check working directory and create .env
      run: |
        echo "Current working directory: $(pwd)"
        echo "Contents of current directory:"
        ls -la
        
        if [ ! -f ".env.example" ]; then
          echo ".env.example not found! Creating one..."
          echo "HUGGINGFACE_API_KEY=your_api_key" > .env.example
        fi
        
        echo "Contents of .env.example:"
        cat .env.example
        
        # Create .env file
        cp .env.example .env
        echo "Created .env file:"
        cat .env
        
        # Replace API key
        sed -i "s|your_api_key|${{ secrets.HUGGINGFACE_API_KEY }}|g" .env
        echo "Updated .env file:"
        cat .env
        
        # Verify file exists with full path
        echo "Checking if .env exists:"
        ls -la .env
        echo "Full path: $(pwd)/.env"

    - name: Upload .env file
      uses: actions/upload-artifact@v4
      with:
        name: env-file
        path: ${{ github.workspace }}/.env
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Run tests
      run: flutter test
      
    - name: Build APK
      run: flutter build apk --release
      
    - name: Build App Bundle
      run: flutter build appbundle --release
      
    - name: Upload APK to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: testers
        file: build/app/outputs/flutter-apk/app-release.apk
        releaseNotes: |
          Changes in this build:
          ${{ github.event.head_commit.message }}