name: Build and Deploy Flutter Android App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
        
    - name: Check if .env.example exists
      run: |
        if [ ! -f ".env.example" ]; then
          echo ".env.example not found! Creating one..."
          echo "HUGGINGFACE_API_KEY=your_api_key" > .env.example
        fi
        cat .env.example

    - name: Copy .env.example to .env
      run: |
        cp .env.example .env
        echo "Created .env file:"
        cat .env

    - name: Replace API key from GitHub Secrets
      run: |
        sed -i "s|your_api_key|${{ secrets.HUGGINGFACE_API_KEY }}|g" .env
        echo "Updated .env file:"
        cat .env

    - name: Verify .env file exists
      run: |
        if [ -f ".env" ]; then
          echo ".env file exists and contains:"
          cat .env
        else
          echo ".env file not found!"
          exit 1
        fi

    - name: Upload .env file
      uses: actions/upload-artifact@v4
      with:
        name: env-file
        path: .env
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Run tests
      run: flutter test
      
    - name: Build APK
      run: flutter build apk --release
      
    - name: Build App Bundle
      run: flutter build appbundle --release
      
    - name: Upload APK to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: testers
        file: build/app/outputs/flutter-apk/app-release.apk
        releaseNotes: |
          Changes in this build:
          ${{ github.event.head_commit.message }}